---
title: "Package MSM"
author: "Shuyu, Marame, Kevin, Théo, Florence"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=TRUE, results="verbatim")
```

```{r}
library(tidyverse)
library(msm)
library(survival)
#Import les données
data <- read.csv("data/TCGA-CDR_data.csv")
# Creation de donnee simule
covar_sim <- sample(c(0,1),1000,replace=TRUE)
covar <-  sample(c(0,1),11160,replace=TRUE)

#convert qq colonnes en numerique depuis les facteurs.
data$DSS.time <- as.numeric(as.character(data$DSS.time))
data$DSS <- as.numeric(as.character(data$DSS))
data$PFI.time <- as.numeric(as.character(data$PFI.time))
data$PFI <- as.numeric(as.character(data$PFI))

# Chqnge les valeurs de DSS.time et PFI.time au NA, (Car pas de sens un temps 0)
# ou si PFI.time est plus grand que DSS.time car aussi pas de sens.  
data$DSS.time[data$DSS.time==0] <- NA #enlever les suivis nuls
data$PFI.time[data$PFI.time==0] <- NA #enlever les suivis nuls
data$DSS.time[data$PFI.time > data$DSS.time] <- NA
data$PFI.time[data$PFI.time > data$DSS.time] <- NA


# Creation de colonnes pour la création de dataframe de matrice de transition
pfiNotDead.time <- data$PFI.time/365.25
pfiNotDead <- data$PFI
pfiNotDead[data$PFI.time==data$DSS.time] <- 0
dssDirect.time <- data$DSS.time/365.25
dssDirect <- data$DSS
dssDirect[!data$PFI.time==data$DSS.time] <- 0
dssRelapse.time <- (data$DSS.time-data$PFI.time)/365.25
dssRelapse.time[pfiNotDead==0] <- 0
dssRelapse <- data$DSS
dssRelapse[data$PFI.time==data$DSS.time] <- 0


# Recode les levels du stage du tumeur pour avoir moins de niveau.  
# Fait qu'il y a seulement stage 1/2, 3/4 et NA; ou 1/2, 3/4, autre et NA  
stage <- as.factor(data$ajcc_pathologic_tumor_stage)
levels(stage) <- c("NA","NA","NA","NA","I - II","I - II","other","I - II","I - II","I - II","I - II","I - II","I - II","I - II","III - IV","III - IV","III - IV","III - IV","III - IV","III - IV","III - IV","III - IV","other")
stageBis <- as.factor(data$clinical_stage)
levels(stageBis) <- c("NA","NA","NA","I - II","I - II","I - II","III - IV","III - IV","III - IV",rep("I - II",14),rep("III - IV",6),"I - II",rep("III - IV",4))
stage <- sapply(1:length(stage),function(i){
  if(stage[i]=="NA") return(stageBis[i])
  else return(stage[i])
})

# Creation d'un nouveau dataframe plus petit et facile a manipuler.  
df_new <- data.frame("Patient"=data$X,
                     "DSS"=data$DSS,"DSS.time"=data$DSS.time/365.25,
                     "PFI"=data$PFI,"PFI.time"=data$PFI.time/365.25,
                     "T01"=pfiNotDead,"T01.time"=pfiNotDead.time,
                     "T02"=dssDirect,"T02.time"=dssDirect.time,
                     "T12"=dssRelapse,"T12.time"=dssRelapse.time,
                     stage,"var_nulle"=as.character(covar),"gender"=data$gender,"age"=data$age_at_initial_pathologic_diagnosis,"type"=data$type)

# Enleve les NA
df_new <- df_new[-which(apply(df_new,1,function(x) any(is.na(x)))),]
dim(df_new)
# Enleve les stage qui ont le niveau NA ou other
df_new <- df_new[-which(is.element(df_new$stage,c("NA","other"))),]
df_new$stage <- factor(df_new$stage,c("I - II","III - IV"))
dim(df_new)
df_new$age <- as.numeric(as.character(df_new$age))
df_new <- df_new[-which(is.na(df_new$age)),] #nettoyage des NA de l'age
# Dois les converti depuis factors pour qu'ils soit bien selectionner dans le boucle for
df_new <- df_new %>% mutate_at(c('type','stage','age','var_nulle','gender'), as.character)
```

```{r}


#* Section plus compliquer a comprendre
#* Chaque personne peut atteindre max de 3 phase,  soit 1-1 (censure pour PFI et DSS), 1-2-2 (censure pour DSS), 
#* 1-3 (pas de censure, PFI.time == DSS.time), ou 1-2-3 (pas de censure, PFI.time != DSS.time) selon leur prognosis et leur censure. 
#* Donc il y a 3 matrice qui sont cree chaqu'un avec 4 colonne: indiv, time, state et type
#* Dans un boucle for du longeur du dataframe des patients (qu'on n'a pas retirer) pour chaque matrix, on regarde quel phase doit placer le patient
#* et on lui donne le bonne 'state'.  Si le personne n'a pas de troisieme phase, on met NA, qu'on enlevera apres.  
state1 <- matrix(nrow =length(df_new$Patient),ncol = 8,dimnames = list(1:length(df_new$Patient),c("indiv","time","state","type",'var_nulle','stage','age','gender'))) 
state1 <- state2 <- state3<- as.data.frame(state1)
for(i in 1:length(df_new[,1])){
  state1[i,] <- c(df_new$Patient[i],0,1,df_new$type[i],covar[i],df_new$stage[i], df_new$age[i], df_new$gender[i])
  state2[i,] <- 
    if((df_new$T01.time[i] < df_new$T02.time[i]) & df_new$T01[i]==1) c(df_new$Patient[i],df_new$T01.time[i],2,df_new$type[i],covar[i],df_new$stage[i], df_new$age[i], df_new$gender[i])
  else if (df_new$T02[i] == 1) c(df_new$Patient[i],df_new$T02.time[i],3,df_new$type[i],covar[i],df_new$stage[i], df_new$age[i], df_new$gender[i])
  else c(df_new$Patient[i],df_new$T02.time[i],1,df_new$type[i],covar[i],df_new$stage[i], df_new$age[i], df_new$gender[i])
  state3[i,] <- 
    if((df_new$T01.time[i] < df_new$T02.time[i]) & df_new$T01[i]==1){
      if (df_new$T12.time[i] > 0 & df_new$T12[i]==1) c(df_new$Patient[i],df_new$T12.time[i]+df_new$T01.time[i],3,df_new$type[i],covar[i],df_new$stage[i], df_new$age[i], df_new$gender[i])
      else c(df_new$Patient[i],df_new$T12.time[i]+df_new$T01.time[i],2,df_new$type[i],covar[i],df_new$stage[i], df_new$age[i], df_new$gender[i])
    }
  else c(NA,NA,NA,NA)
}

# Combine les 3 matrices 
# Ajoute les colonnes depuis df_new pour utiliser les covariants
# Convert les donnees en bonne type de donnees
# Enleve les donnees qui on un 'state' == NA
df_msm <- rbind(state1,state2,state3)
df_msm$indiv <- as.integer(df_msm$indiv)
df_msm$time <- as.numeric(df_msm$time)
df_msm$state <- as.numeric(df_msm$state)
df_msm$var_nulle <- as.numeric(df_msm$var_nulle)
df_msm$age <- as.numeric(df_msm$age)
df_msm$gender <- as.factor(df_msm$gender)
df_msm$stage <- as.factor(df_msm$stage)
df_msm <- df_msm[-which(is.na(df_msm$state)),]

# Ordonner le dataframe par individu et le temps de chaque transition.  
df_msm <- df_msm[order(df_msm$indiv,df_msm$time),]


# Test pour verifier les donnees sont correct
# unique(df_msm[df_msm$stage=='III - IV'& df_msm$type=='PAAD',]$indiv)
# unique(df_new[df_new$stage=='III - IV'& df_new$type=='PAAD',]$Patient)


# Regarde le table de transition d'etats et cree un Q matrix de base.  
statetable.msm(state, indiv, df_msm)
Qmat <- matrix(c(1,1,1,0,1,1,0,0,0),ncol=3,byrow = TRUE)
par(mfrow = c(1,1))
test_msm <- msm(state~time, subject=indiv,data = df_msm[df_msm$type == 'BRCA',], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3,covariates = ~age)
hazard.msm(test_msm)
layout(1, respect=TRUE)
plot(test_msm, legend.pos = c(8,.5))
```

# BRCA
## a vide

```{r}
layout(matrix(1:3,1), respect=TRUE)
test_msm_brca <- msm(state~time, subject=indiv,data = df_msm[df_msm$type == 'BRCA',], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3)
test_msm_brca
summary(test_msm_brca)
plot.prevalence.msm(test_msm_brca)
#plot(test_msm_brca )
```


## Var nulle

```{r}
test_msm_brca_nul <- msm(state~time, subject=indiv,data = df_msm[df_msm$type == 'BRCA',], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3,covariates = ~var_nulle)
#test_msm_brca_nul
summary(test_msm_brca_nul)$hazard
#plot.prevalence.msm(test_msm_brca_nul)
```

## Stage

```{r}
test_msm_brca_stage <- msm(state~time, subject=indiv,data = df_msm[df_msm$type == 'BRCA',], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3,covariates = ~stage)
#test_msm_brca_stage
summary(test_msm_brca_stage)$hazard
#plot.prevalence.msm(test_msm_brca_stage)

```

# PAAD
## a vide

```{r}
layout(matrix(1:3,1), respect=TRUE)
test_msm_paad <- msm(state~time, subject=indiv,data = df_msm[df_msm$type == 'PAAD',], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3)
test_msm_paad
plot.prevalence.msm(test_msm_paad)
```

## var nulle

```{r}
layout(matrix(1:3,1), respect=TRUE)
test_msm_paad_nul <- msm(state~time, subject=indiv,data = df_msm[df_msm$type == 'PAAD',], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3,covariates = ~var_nulle)
#test_msm_paad_nul
summary(test_msm_paad_nul)$hazard
#plot.prevalence.msm(test_msm_paad_nul)
```

## Stage

```{r}
test_msm_paad_stage <- msm(state~time, subject=indiv,data = df_msm[df_msm$type == 'PAAD',], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3,covariates = ~stage)
summary(test_msm_paad_stage)$hazard
#plot.prevalence.msm(test_msm_paad_stage)
```



# OV
## a vide

```{r}
layout(matrix(1:3,1), respect=TRUE)
test_msm_ov <- msm(state~time, subject=indiv,data = df_msm[df_msm$type == 'OV',], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3)
test_msm_ov
summary(test_msm_ov)
plot.prevalence.msm(test_msm_ov)
#plot(test_msm_brca )
```


## Var nulle

```{r}
test_msm_ov_nul <- msm(state~time, subject=indiv,data = df_msm[df_msm$type == 'OV',], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3,covariates = ~var_nulle)

summary(test_msm_ov_nul)$hazard

```

## Stage

```{r}
test_msm_ov_stage <- msm(state~time, subject=indiv,data = df_msm[df_msm$type == 'OV',], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3,covariates = ~stage)
test_msm_ov_stage
```


# Comparaison

## Stage

```{r}
# summary(test_msm_brca_stage)$hazard
# summary(test_msm_paad_stage)$hazard
# summary(test_msm_ov_stage)$hazard

# tableau des HR +IC
cancer_type = c("BRCA","OV","PAAD")
#trans= c("01","02","12")
res_msm_stage = data.frame("Type"=NA,"HR T01"=NA, "low T01"= NA,"high T01"=NA, "HR T02"=NA, "low T02"= NA,"high T02"=NA,"HR T12"=NA, "low T12"= NA,"high T12"=NA)
for(i in 1:length(cancer_type)){
msm_stage = msm(state~time, subject=indiv,data = df_msm[df_msm$type == cancer_type[i],], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3,covariates = ~stage)
res_msm_stage[i,] =c ((cancer_type[i]), round(summary(msm_stage)$hazard$`stageIII - IV`[1],3), round(summary(msm_stage)$hazard$`stageIII - IV`[4],3), round(summary(msm_stage)$hazard$`stageIII - IV`[7],3), round(summary(msm_stage)$hazard$`stageIII - IV`[2],3), round(summary(msm_stage)$hazard$`stageIII - IV`[5],3), round(summary(msm_stage)$hazard$`stageIII - IV`[8],3), round(summary(msm_stage)$hazard$`stageIII - IV`[3],3), round(summary(msm_stage)$hazard$`stageIII - IV`[6],3), round(summary(msm_stage)$hazard$`stageIII - IV`[9],3))
}
res_msm_stage
```


## var nulle
```{r}
# summary(test_msm_brca_nul)$hazard
# summary(test_msm_paad_nul)$hazard

# tableau des HR +IC
cancer_type=c("BRCA","OV","PAAD")
#trans= c("01","02","12")
res_msm_var_nulle=data.frame("Type"=NA,"HR T01"=NA, "low T01"= NA,"high T01"=NA, "HR T02"=NA, "low T02"= NA,"high T02"=NA,"HR T12"=NA, "low T12"= NA,"high T12"=NA)
for(i in 1:length(cancer_type)){
  msm_var_nulle = msm(state~time, subject=indiv,data = df_msm[df_msm$type == cancer_type[i],], gen.inits = TRUE,qmatrix= Qmat, deathexact = 3,covariates = ~var_nulle)
  res_msm_var_nulle[i,] = c((cancer_type[i]), round(summary(msm_var_nulle)$hazard$var_nulle[1],3), round(summary(msm_var_nulle)$hazard$var_nulle[4],3), round(summary(msm_var_nulle)$hazard$var_nulle[7],3), round(summary(msm_var_nulle)$hazard$var_nulle[2],3), round(summary(msm_var_nulle)$hazard$var_nulle[5],3), round(summary(msm_var_nulle)$hazard$var_nulle[8],3), round(summary(msm_var_nulle)$hazard$var_nulle[3],3), round(summary(msm_var_nulle)$hazard$var_nulle[6],3), round(summary(msm_var_nulle)$hazard$var_nulle[9],3))
}
res_msm_var_nulle

```

```{r}
#effectifs des transitions

statetable.msm(state, indiv, df_msm)

data_brca = df_msm[df_msm$type == 'BRCA',]
statetable.msm(state, indiv, data_brca)
data_brca_2 = data_brca[data_brca$stage=='III - IV',]
statetable.msm(state, indiv, data_brca_2)


data_paad = df_msm[df_msm$type == 'PAAD',]
statetable.msm(state, indiv, data_paad)
data_paad_2=data_paad[data_paad$stage=='III - IV',]
statetable.msm(state, indiv, data_paad_2)

data_ov = df_msm[df_msm$type == 'OV',]
statetable.msm(state, indiv, data_ov)
data_ov_2 = data_ov[data_ov$stage=='III - IV',]
statetable.msm(state, indiv, data_ov_2)

```



```{r}
# controle effectifs de_new df_msm
# data_brca = df_new[df_new$type == 'BRCA',]
# data_paad = df_new[df_new$type == 'PAAD',]
# data_paad_2=data_paad[data_paad$stage=='III - IV',]
# dim(data_paad_2)
# unique(data_paad_2$Patient)
# 
# data_prov2 = df_msm[df_msm$type == 'PAAD',]
# data_prov2 = data_prov2[data_prov2$stage=='III - IV',]
# length(unique(data_prov2$indiv))

# data_paad = df_new[df_new$type == 'OV',]
# data_paad_2=data_paad[data_paad$stage=='III - IV',]
# dim(data_paad_2)
# unique(data_paad_2$Patient)
# 
# data_prov2 = df_msm[df_msm$type == 'OV',]
# data_prov2 = data_prov2[data_prov2$stage=='III - IV',]
# length(unique(data_prov2$indiv))

# data_prov2 = df_msm[df_msm$type == 'OV',]
# data_prov2 = data_prov2[data_prov2$stage=='I - II',]
# length(unique(data_prov2$indiv))
```

### Modèles de cox Marginaux

## Var nulle

```{r}

#HR des modeles de cox marginaux var nulle
cancer_type = c("BRCA","OV","PAAD")
#trans= c("01","02","12")
res = data.frame("Type"=NA,"HR T01"=NA, "low T01"= NA,"high T01"=NA, "HR T02"=NA, "low T02"= NA,"high T02"=NA,"HR T12"=NA, "low T12"= NA,"high T12"=NA)
for(i in 1:length(cancer_type)){
  cox01_var_nulle = coxph(Surv(T01.time,T01)~var_nulle, data = df_new[df_new$type == cancer_type[i],])
  cox02_var_nulle = coxph(Surv(T02.time,T02)~var_nulle, data = df_new[df_new$type == cancer_type[i],])
  cox12_var_nulle = coxph(Surv(T12.time,T12)~var_nulle, data = df_new[df_new$type == cancer_type[i],])
  res[i,]=c((cancer_type[i]), round(summary(cox01_var_nulle)$conf.int[1],3),round(summary(cox01_var_nulle)$conf.int[3],3),round(summary(cox01_var_nulle)$conf.int[4],3),
            round(summary(cox02_var_nulle)$conf.int[1],3),round(summary(cox02_var_nulle)$conf.int[3],3),round(summary(cox02_var_nulle)$conf.int[4],3),
            round(summary(cox12_var_nulle)$conf.int[1],3),round(summary(cox12_var_nulle)$conf.int[3],3),round(summary(cox12_var_nulle)$conf.int[4],3))
  
}
res

#courbes KM
layout(matrix(1:9,3, byrow = T), respect=TRUE)
for(i in 1:length(cancer_type)){
  plot(survfit(Surv(T01.time,T01)~var_nulle, data = df_new[df_new$type == cancer_type[i],]), col=c(2,3), main=paste0(cancer_type[i],"T01"), mark.time = T, conf.int = T)
  plot(survfit(Surv(T02.time,T02)~var_nulle, data = df_new[df_new$type == cancer_type[i],]), col=c(2,3),main=paste0(cancer_type[i],"T02"),mark.time = T, conf.int = T)
  plot(survfit(Surv(T12.time,T12)~var_nulle, data = df_new[df_new$type == cancer_type[i],]), col=c(2,3),main=paste0(cancer_type[i],"T12"),mark.time = T, conf.int = T)
  c(plot)
}







```

## Stage

```{r}

#HR des modeles de cox marginaux stage
cancer_type = c("BRCA","OV","PAAD")
#trans= c("01","02","12")
res = data.frame("Type"=NA,"HR T01"=NA, "low T01"= NA,"high T01"=NA, "HR T02"=NA, "low T02"= NA,"high T02"=NA,"HR T12"=NA, "low T12"= NA,"high T12"=NA)
for(i in 1:length(cancer_type)){
  cox01_stage = coxph(Surv(T01.time,T01)~stage, data = df_new[df_new$type == cancer_type[i],])
  cox02_stage = coxph(Surv(T02.time,T02)~stage, data = df_new[df_new$type == cancer_type[i],])
  cox12_stage = coxph(Surv(T12.time,T12)~stage, data = df_new[df_new$type == cancer_type[i],])
  res[i,]=c((cancer_type[i]), round(summary(cox01_stage)$conf.int[1],3),round(summary(cox01_stage)$conf.int[3],3),round(summary(cox01_stage)$conf.int[4],3),
            round(summary(cox02_stage)$conf.int[1],3),round(summary(cox02_stage)$conf.int[3],3),round(summary(cox02_stage)$conf.int[4],3),
            round(summary(cox12_stage)$conf.int[1],3),round(summary(cox12_stage)$conf.int[3],3),round(summary(cox12_stage)$conf.int[4],3))
  
}
res

#courbes KM
layout(matrix(1:9,3, byrow = T), respect=TRUE)
for(i in 1:length(cancer_type)){
  plot(survfit(Surv(T01.time,T01)~stage, data = df_new[df_new$type == cancer_type[i],]), col=c(2,3), main=paste0(cancer_type[i],"T01"), mark.time = T, conf.int = T)
  plot(survfit(Surv(T02.time,T02)~stage, data = df_new[df_new$type == cancer_type[i],]), col=c(2,3),main=paste0(cancer_type[i],"T02"),mark.time = T, conf.int = T)
  plot(survfit(Surv(T12.time,T12)~stage, data = df_new[df_new$type == cancer_type[i],]), col=c(2,3),main=paste0(cancer_type[i],"T12"),mark.time = T, conf.int = T)
  c(plot)
}
```